project:
  name: linting-and-testing-workshop
  package_lambda: false
  # Update this section with regions you wish to use
  regions:
  - eu-west-1
tests:
  default:
    template: ./vpc-and-security-group.yaml
