AWSTemplateFormatVersion: '2010-09-09'

Description: AWS CloudFormation workshop - Conditions at property level (uksb-1q9p31idr).
# Add your code here!
Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  EnvType:
    Type: String
    Description: Specify the environment type of the stack
    AllowedValues:
      - test
      - prod
    Default: test
    ConstraintDescription: Specify either test or prod

Conditions:
  IsProduction: !Equals
    - !Ref EnvType
    - prod

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !If [IsProduction, t2.small, t2.micro]
