AWSTemplateFormatVersion: '2010-09-09'

Description: AWS CloudFormation workshop - Mappings (uksb-1q9p31idr).

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Amazon EC2 Configuration'
        Parameters:
          # Remove InstanceType group.
          - InstanceType
          - AmiID
    ParameterLabels:
      # Remove the InstanceType parameter label.
      InstanceType:
        default: 'Type of EC2 Instance'
      AmiID:
        default: 'Amazon Machine Image ID'

Parameters:
  # Replace the InstanceType parameter with EnvironmentType parameter.
  EnvironmentType:
    Description: 'Specify the environment type of the stack.'
    Type: String
    Default: Test
    AllowedValues:
      - Dev
      - Test
      - Prod
    ConstraintDescription: 'Specify either Test or Prod'

  AmiID:
    Type: AWS::EC2::Image::Id
    Description: 'The ID of the AMI.'

# Add a Mappings section here!

Mappings:
  EnvironmentToInstanceType:
    Dev:
      InstanceType: t2.nano
    Test:
      InstanceType: t2.micro
    Prod:
      InstanceType: t2.small

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiID
      # Update the 'InstanceType' property with !FindInMap function
      InstanceType: !FindInMap
        - EnvironmentToInstanceType
        - !Ref EnvironmentType
        - InstanceType

      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref EnvironmentType, webserver]] # replace the 'InstanceType' with 'EnvironmentType'
